# Generated by Django 4.0.4 on 2022-05-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_moderatorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeratorProfile',
        ),
    ]
