# Generated by Django 4.0.4 on 2022-05-26 16:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comms', '0002_remove_question_likes_remove_question_title_tag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Rating',
        ),
    ]
